import {isRTL} from '../src/i18n/locale';
import React,{useState} from 'react';
import {View,Text,TextInput,Pressable,ScrollView,StyleSheet,ActivityIndicator,Alert} from 'react-native';
import {router} from 'expo-router';
import {sendAIMessage,ChatReply,createGoal,generateGoalPlan,createAction} from '../src/lib/api';
import {useI18n} from '../src/i18n';
import {screenText} from '../src/i18n/screens';
export default function AIChat(){
 const {language}=useI18n(); const tx=(key:string)=>screenText(language,key);
 const [draft,setDraft]=useState(''); const [busy,setBusy]=useState(false); const [reply,setReply]=useState<ChatReply|null>(null);
 const [goalTitle,setGoalTitle]=useState(''); const [savingGoal,setSavingGoal]=useState(false); const [savedActions,setSavedActions]=useState<string[]>([]);
 async function send(){const msg=draft.trim();if(!msg||busy)return;setBusy(true);setDraft('');try{const result=await sendAIMessage(msg);setReply(result);setGoalTitle('');setSavedActions([])}catch(e:any){Alert.alert('LIFE OS',e?.message??'Please try again.');setDraft(msg)}finally{setBusy(false)}}
 async function saveAction(action:string){try{await createAction({title:action,description:'Suggested during a reflection. Adjust it to make it realistic for you.',estimatedMinutes:10,effort:2,complexity:1,expectedImpact:5,confidence:5});setSavedActions(x=>[...x,action]);Alert.alert('LIFE OS',tx('saved'))}catch(e:any){Alert.alert('LIFE OS',e?.message??'Please try again.')}}
 async function makeGoal(){if(!goalTitle.trim()||savingGoal)return;setSavingGoal(true);try{const g=await createGoal({title:goalTitle.trim(),description:'Goal clarified from a reflection with LIFE OS.',goalType:'OUTCOME',importance:7,motivation:7});await generateGoalPlan(g.id);Alert.alert('LIFE OS',tx('goalCreated'));router.push('/today')}catch(e:any){Alert.alert('LIFE OS',e?.message??'Could not create the goal.')}finally{setSavingGoal(false)}}
 return <ScrollView contentContainerStyle={[s.page,{direction:(isRTL(language)?'rtl':'ltr')}]}><Text style={s.eyebrow}>LIFE OS · {tx('reflectionEyebrow')}</Text><Text style={s.title}>{tx('reflectionTitle')}</Text><Text style={s.body}>{tx('reflectionBody')}</Text>
 {reply&&<View style={s.card}><Text style={s.reply}>{reply.message}</Text>{reply.insight&&<Text style={s.insight}>{reply.insight}</Text>}{reply.questions.map((q,i)=><Text key={i} style={s.question}>• {q}</Text>)}{reply.suggested_actions.map((a,i)=><View key={i} style={s.actionRow}><Text style={s.action}>{tx('nextStep')} {a}</Text><Pressable onPress={()=>saveAction(a)} disabled={savedActions.includes(a)} style={s.saveAction}><Text style={s.saveActionText}>{savedActions.includes(a)?tx('saved'):tx('saveToday')}</Text></Pressable></View>)}<View style={s.goalBox}><Text style={s.goalHeading}>{tx('transformGoal')}</Text><TextInput value={goalTitle} onChangeText={setGoalTitle} placeholder={tx('goalQuestion')} style={s.goalInput}/><Pressable disabled={!goalTitle.trim()||savingGoal} onPress={makeGoal} style={[s.goalButton,(!goalTitle.trim()||savingGoal)&&{opacity:.5}]}>{savingGoal?<ActivityIndicator color="#fff"/>:<Text style={s.goalButtonText}>{tx('createPlan')}</Text>}</Pressable></View><Text style={s.caption}>{reply.provider==='safe-fallback'?tx('aiFallback'):tx('aiReply')}</Text></View>}
 <TextInput value={draft} onChangeText={setDraft} multiline placeholder={tx('conversationPlaceholder')} style={s.input}/><Pressable onPress={send} disabled={busy||!draft.trim()} style={[s.button,(busy||!draft.trim())&&{opacity:.5}]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>{tx('talk')}</Text>}</Pressable><Text style={s.caption}>{tx('safetyNote')}</Text></ScrollView>
}
const s=StyleSheet.create({page:{padding:24,paddingTop:60,backgroundColor:'#faf9f6',flexGrow:1},eyebrow:{letterSpacing:2,fontWeight:'700',fontSize:11,opacity:.6},title:{fontSize:32,fontWeight:'700',marginTop:12},body:{fontSize:16,lineHeight:24,opacity:.7,marginTop:12,marginBottom:22},card:{backgroundColor:'#fff',padding:18,borderRadius:18,marginBottom:18},reply:{fontSize:17,lineHeight:25},insight:{marginTop:12,fontWeight:'600'},question:{marginTop:12,lineHeight:22},action:{marginTop:10,backgroundColor:'#f0eee8',padding:12,borderRadius:10,lineHeight:21},actionRow:{marginTop:8},saveAction:{alignSelf:'flex-start',padding:9,marginTop:5,borderRadius:9,backgroundColor:'#e7e4dc'},saveActionText:{fontWeight:'600',fontSize:12},goalBox:{marginTop:18,padding:15,borderRadius:14,borderWidth:1,borderColor:'#e5e2dc'},goalHeading:{fontWeight:'700',fontSize:16,marginBottom:10},goalInput:{backgroundColor:'#fff',padding:12,borderRadius:10,borderWidth:1,borderColor:'#e5e2dc'},goalButton:{marginTop:10,backgroundColor:'#171717',padding:13,borderRadius:10,alignItems:'center'},goalButtonText:{color:'#fff',fontWeight:'700'},input:{minHeight:110,backgroundColor:'#fff',borderRadius:14,padding:15,textAlignVertical:'top',fontSize:16},button:{marginTop:12,backgroundColor:'#171717',padding:16,borderRadius:14,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'700',fontSize:16},caption:{fontSize:12,opacity:.55,lineHeight:18,marginTop:16}});
