import {isRTL} from '../src/i18n/locale';
import React,{useEffect,useState} from 'react';
import {View,Text,StyleSheet,ScrollView,Pressable,ActivityIndicator} from 'react-native';
import {router} from 'expo-router';
import {getInsights,getWeeklyReview} from '../src/lib/api'; import {useI18n} from '../src/i18n'; import {screenText} from '../src/i18n/screens';

export default function Insights(){
 const {language,t}=useI18n(); const tx=(key:string)=>screenText(language,key);
 const [data,setData]=useState<any>(null); const [review,setReview]=useState<any>(null); const [busy,setBusy]=useState(true);
 useEffect(()=>{Promise.all([getInsights(),getWeeklyReview()]).then(([i,r])=>{setData(i);setReview(r)}).catch(()=>{}).finally(()=>setBusy(false))},[]);
 return <ScrollView contentContainerStyle={[s.page,{direction:(isRTL(language)?'rtl':'ltr')}]}><Text style={s.eyebrow}>{tx('insightsEyebrow')}</Text><Text style={s.title}>{tx('insightsTitle')}</Text><Text style={s.intro}>{tx('insightsIntro')}</Text>{busy?<ActivityIndicator/>:<><Text style={s.section}>{tx('recentPatterns')}</Text>{(data??[]).slice(0,3).map((i:any)=><View style={s.card} key={i.id??i.title}><Text style={s.cardTitle}>{i.title}</Text><Text style={s.cardBody}>{i.description}</Text><Text style={s.conf}>{tx('confidence')}: {Math.round((i.confidence??0)*100)}%</Text></View>)}{review&&<><Text style={s.section}>{tx('review')}</Text><View style={s.review}><Text style={s.reviewTitle}>{tx('weeklyQuestions')}</Text>{review.questions?.map((q:string,n:number)=><Text key={q} style={s.question}>{n+1}. {q}</Text>)}</View><Text style={s.section}>{tx('priorities')}</Text>{(review.priorities??[]).map((p:any)=><View style={s.priority} key={p.id}><Text style={s.priorityText}>{p.title}</Text></View>)}</>}</>}<View style={s.nav}><Pressable onPress={()=>router.push('/today')}><Text style={s.navText}>{t('today')}</Text></Pressable><Pressable onPress={()=>router.push('/goals')}><Text style={s.navText}>{t('goals')}</Text></Pressable><Pressable onPress={()=>router.push('/map')}><Text style={s.navText}>{t('map')}</Text></Pressable></View></ScrollView>
}
const s=StyleSheet.create({page:{padding:24,paddingTop:65,backgroundColor:'#faf9f6',minHeight:'100%'},eyebrow:{letterSpacing:2,fontWeight:'700',opacity:.5},title:{fontSize:34,lineHeight:40,fontWeight:'700',marginTop:10},intro:{marginTop:14,opacity:.6,lineHeight:21},section:{fontSize:21,fontWeight:'700',marginTop:30,marginBottom:12},card:{backgroundColor:'#fff',padding:18,borderRadius:16,marginBottom:10},cardTitle:{fontSize:17,fontWeight:'700'},cardBody:{marginTop:7,lineHeight:21,opacity:.7},conf:{marginTop:12,fontSize:12,opacity:.45},review:{backgroundColor:'#171717',padding:20,borderRadius:18},reviewTitle:{color:'#fff',fontWeight:'700',fontSize:18,marginBottom:10},question:{color:'#fff',opacity:.78,lineHeight:24,marginTop:6},priority:{backgroundColor:'#fff',padding:16,borderRadius:14,marginBottom:8},priorityText:{fontWeight:'700'},nav:{flexDirection:'row',justifyContent:'space-around',marginTop:30,paddingTop:20,borderTopWidth:1,borderTopColor:'#e5e2dc'},navText:{fontWeight:'700'} });
