import {isRTL} from '../src/i18n/locale';
import React,{useCallback,useState} from 'react';
import {View,Text,TextInput,Pressable,ScrollView,StyleSheet,Alert,Switch} from 'react-native'; import {useFocusEffect} from 'expo-router'; import {getMemories,saveMemory,deleteMemory} from '../src/lib/api'; import {useI18n} from '../src/i18n'; import {screenText} from '../src/i18n/screens';
type Memory={id:string;category:string;content:string;userConfirmed:boolean};
export default function Memories(){const {language}=useI18n(); const tx=(key:string)=>screenText(language,key);const [items,setItems]=useState<Memory[]>([]);const [category,setCategory]=useState('preferência');const [content,setContent]=useState('');const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);
 const refresh=useCallback(()=>{getMemories().then(setItems).catch(()=>Alert.alert(tx('memoryTitle'),tx('memoryLoadError')));},[]);useFocusEffect(refresh);
 async function add(){if(!consent){Alert.alert(tx('consentNeeded'),tx('consentPrompt'));return}if(!content.trim())return;setBusy(true);try{await saveMemory(category.trim(),content.trim());setContent('');setConsent(false);refresh()}catch(e:any){Alert.alert('Error',e?.message??tx('memorySaveError'))}finally{setBusy(false)}}
 async function remove(id:string){try{await deleteMemory(id);refresh()}catch{Alert.alert('Error',tx('memoryDeleteError'))}}
 return <ScrollView contentContainerStyle={[s.page,{direction:(isRTL(language)?'rtl':'ltr')}]}><Text style={s.eyebrow}>{tx('memoryEyebrow')}</Text><Text style={s.title}>{tx('memoryTitle')}</Text><Text style={s.body}>{tx('memoryBody')}</Text><Text style={s.label}>{tx('category')}</Text><TextInput value={category} onChangeText={setCategory} style={s.input}/><Text style={s.label}>{tx('memoryQuestion')}</Text><TextInput value={content} onChangeText={setContent} multiline maxLength={500} placeholder="Ex.: prefiro passos pequenos ao fim do dia" style={[s.input,{minHeight:90,textAlignVertical:'top'}]}/><View style={s.row}><Text style={s.consentText}>{tx('consent')}</Text><Switch value={consent} onValueChange={setConsent}/></View><Pressable disabled={!consent||!content.trim()||busy} onPress={add} style={s.button}><Text style={s.buttonText}>{busy?tx('saving'):tx('saveMemory')}</Text></Pressable><Text style={s.section}>{tx('savedMemories')}</Text>{items.length===0?<Text style={s.body}>{tx('noMemories')}</Text>:items.map(m=><View key={m.id} style={s.card}><Text style={s.label}>{m.category}</Text><Text style={s.cardText}>{m.content}</Text><Pressable onPress={()=>remove(m.id)}><Text style={s.delete}>{tx('deleteMemory')}</Text></Pressable></View>)}</ScrollView>}
const s=StyleSheet.create({page:{padding:24,paddingTop:60,backgroundColor:'#faf9f6',flexGrow:1},eyebrow:{letterSpacing:2,fontWeight:'700',fontSize:11,opacity:.6},title:{fontSize:32,fontWeight:'700',marginTop:12},body:{fontSize:15,lineHeight:23,opacity:.7,marginTop:12,marginBottom:16},label:{fontSize:13,fontWeight:'700',marginTop:10,marginBottom:6},input:{backgroundColor:'#fff',borderRadius:12,padding:13,fontSize:16},row:{flexDirection:'row',alignItems:'center',gap:10,marginTop:14},consentText:{flex:1,lineHeight:20},button:{marginTop:14,backgroundColor:'#171717',padding:15,borderRadius:13,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'700'},section:{fontSize:21,fontWeight:'700',marginTop:28,marginBottom:10},card:{backgroundColor:'#fff',padding:16,borderRadius:14,marginBottom:10},cardText:{fontSize:16,lineHeight:22,marginBottom:12},delete:{color:'#a12626',fontWeight:'600'}});
